# Generated by Django 3.2.8 on 2021-10-28 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awward', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
